language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build --stacktrace --info
