language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support
    - android-25

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - chmod +x gradlew
  - ./gradlew clean build --stacktrace --info


notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
