name: Danger Checks

on: pull_request

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set Up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      # https://medium.com/@thiagolopessilva/running-android-unit-testing-on-github-action-with-a-project-that-contains-firebase-dependency-621603363bc1
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > app/google-services.json

      - name: Danger Checks
        run: |
          ./gradlew detekt
          ./gradlew ktlintCheck
          ./gradlew lint
          ./gradlew dependencyUpdates
          cd scripts
          touch ktlint-report-orig.xml
          touch ktlint-report.xml
          python combine_ktlint_reports.py
          cd ..
          gem install bundler
          bundle install
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}